org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Valor
plugin_description=Adds Asset Editor tools to help add and support more ammunition's.
plugin_author=Valor
plugin_website=
plugin_main_entrypoint=com.valor.valors_ammo_util.ValorAmmoUtil
server_version=>=0.5.0 <0.6.0
